CPP 		= g++
CPPFLAGS 	= -Wall -lGL -lglut

all:
	$(CPP) -o lab3 primitivas/Cor.cpp primitivas/Pixel.cpp primitivas/FormaGeometrica2D.cpp primitivas/Circunferencia.cpp primitivas/Retangulo.cpp Teclado.cpp Mouse.cpp Robo.cpp Cenario.cpp Principal.cpp $(CPPFLAGS)

clean:
	rm -rf *o lab3