CPP 		= g++
CPPFLAGS 	= -Wall -lGL -lglut -ltinyxml2

all:
	$(CPP) -o trabalho1_2D infraestrutura/AnalistaXML.cpp modelo/primitivas/Cor.cpp modelo/primitivas/Pixel.cpp modelo/FormaGeometrica2D.cpp modelo/Circunferencia.cpp modelo/Retangulo.cpp controle/Teclado.cpp controle/Mouse.cpp Jogador.cpp Cenario.cpp Programa.cpp $(CPPFLAGS)

clean:
	rm -rf *o trabalho1_2D